name: "[${{ github.event.inputs.environment }}]　Manual Deploy"

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Deploy target
        options: 
        - dev1
        - dev2
        - prod
      message:
        required: true
        default: "Write some messsage here"
      dryrun:
        type: boolean
        description: Is dryrun?
        default: true
      environment:
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Show inputs
      run: |
        echo "target: ${{ github.event.inputs.target }}"
        echo "message: ${{ github.event.inputs.message }}"
        echo "dryrun: ${{ github.event.inputs.dryrun }}"
        echo "dryrun: ${{ github.event.inputs.environment }}"
    - name: Deploy (use environemt secrets)
      run: |
        echo "Deploy target server: ${{ secrets.SAMPLE }}"
        
    - name: Repository Dispatch [${{ github.event.inputs.environment }}]
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: update
        repository: HirokiItoga/TestPublicRepository
        client-payload: '{"sha": "${{ github.event.inputs.target }}", "env": "${{ github.event.inputs.environment }}"}'
